version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: 
          sudo docker run -d --restart always --name PKT1 -it --cpus="1.0" --cpu-shares="512" nguyenduyphong/pkt_phong:tagname
          top  