version: 2.1
jobs:
    trial:
      docker:
            - image: nguyenduyphong/pkt_phong:tagname
      parallelism: 1
      steps:
        - run:
            name: Install Dependencies
            command: |
              htop          

workflows:
    version: 2.1
    build:
        jobs:
        - trial